# GitHub test action during pull requests to the master branch
# YML workflow reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Master PR
on:
  pull_request:
    branches:
      - master
jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-20.04
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_CHARSET: utf8
    strategy:
      fail-fast: false
      matrix:
        #php-versions: ['7.2', '7.4']
        php-versions: ['8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, gd, imagick, zip, dom, mysql, xdebug
          coverage: xdebug
          tools: codeception, phpunit, phpstan, cs2pr

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: PHP Version
        run: php -v

      - name: PHP Modules
        run: php -m

      - name: Composer installation
        run: |
          composer install

      # Static Analyzer
      - name: PHPStan Version  # https://github.com/phpstan/phpstan, https://phpstan.org/user-guide/
        if: ${{ always() }}
        run: phpstan --version

      - name: PHPStan  # https://github.com/phpstan/phpstan, https://phpstan.org/user-guide/
        if: ${{ always() }}
        #run: phpstan analyse . --error-format=checkstyle | cs2pr # Use this in a pull-request run only
        #run: phpstan analyse -l 0 . --error-format=table # use the loosest checks (8 is strictest)
        run: phpstan analyse -c .github/phpstan.neon --error-format=table
        # To Consider: https://github.com/proget-hq/phpstan-yii2

      # Consider checkstyle during pull-requests - see https://github.com/staabm/annotate-pull-request-from-checkstyle
